### ISSUE TITLE
Korrespondenz SMS

### ISSUE THREAD

**Issue by olibrian** [hitobito/hitobito_die_mitte#11]
- [x] F04-19 / F08-07 SMS an einzelne oder mehrere Personen verschicken #34 
- [x] F04-20 Absender per Parteieinheit #35
- [x] F04-21 Korrespondenz auf Personen und Firmen sichtbar, Kommunikationshistorie #37
- [x] F04-22, F04-23, F04-24 Massenversand #38
- [x] Affiliate Link: https://github.com/hitobito/hitobito_die_mitte/issues/116
- [x] SMS delivery notifications in eigenen Job #110
