### ISSUE TITLE
MESSAGE: Auswahl ob per Mail oder physischer Versand

### ISSUE THREAD

**Issue by olibrian** [hitobito/hitobito_die_mitte#129]
Beim Druckauftrag von Rechnungsbriefen soll ausgewählt werden ob ein Druckauftrag (physischer Versand) oder ein Versand per Mail erfolgen soll.

## Aktuelles Verhalten
Im Moment wird ein Druckauftrag erstellt, die Sammelrechnung generiert und per Mail an die Druckerei verschickt.

## Gewünschtes Verhalten
**Druckauftrag:**
* Druckauftrag wird erstellt
  * Mail wird an Druckerei gesendet
* Sammelrechnung wird erstellt

**Versand per Mail**
* Sammelrechnung wird erstellt
* Rechnungen werden per Mail verschickt

# Mockup

Anstelle "Druckauftrag erstellen" ein Dropdown-Button mit "Versand"
![image](https://user-images.githubusercontent.com/9592347/111969151-39bbd400-8afa-11eb-9f99-3a77b3a3c14b.png)

Optionen im Dropdown-Button:
* Durckauftrag
* E-Mail

* Ist die Option "Email" ausgewählt, muss der Benutzer dies Bestätigen:
  * Warnung: brief kann nicht mehr geändert werden nach versand
  * Mail wird an X Empfänger versendet (Y weitere haben keine gültige Email-Adresse)
  * Button "Druckauftrag anzeigen" entfernen.
  * PDF anzeigen zeigt PDF-Vorschau (1 Empfänger, nicht alle)

# Tech-Spec
* [ ] Auf Brief und Rechnung bei "Liefermethode" eine neue Option "E-Mail-Versand". Diesen Schritt als letztes umsetzen, das ist quasi der Feature Toggle. hitobito/hitobito#1432
* [ ] Anzahl Empfänger soll bei Liefermethode "E-Mail-Versand" basierend auf gültigen E-Mail-Adressen berechnet werden. Haushalte haben dabei keine Auswirkung, jede Person wird einzeln gezählt, wie bei SMS. hitobito/hitobito#1433
* [ ] Wenn Liefermethode "E-Mail-Versand" ist, wird Button "Druckauftrag erstellen" nicht angezeigt, sondern stattdessen ein Button "Versenden" hitobito/hitobito#1434
* [ ]  Button "Versenden" hat einen Bestätigungsdialog ala "Brief wird jetzt an XY Personen versendet. YX weitere ohne gültige E-Mail-Adresse bekommen den Brief nicht. Brief kann danach nicht mehr bearbeitet werden." hitobito/hitobito#1434
* [ ] Button "Versenden" triggert dieselben Prozesse wie bei "Druckauftrag erstellen", aber ohne den Umweg via Druckauftrag. D.h. Recipients und ggf. Rechnungen in Background-Job erstellen, Daten zur "Verarbeitung" des Briefs / Rechnungsbriefs aktualisieren. Haushalte sollen dabei keinen Einfluss haben, wie bei SMS. hitobito/hitobito#1434
* [ ] Sobald die Prozesse abgeschlossen sind, werden (bei Briefen / Rechnungsbriefen mit Liefermethode "E-Mail-Versand")  E-Mails an alle MessageRecipients des Briefs / Rechnungsbriefs versendet. hitobito/hitobito#1435
* [ ] Die E-Mails sollen Background-Jobs versendet werden hitobito/hitobito#1435
* [ ] Natürlich soll in jedem E-Mail nur das zum Empfänger passende PDF angehängt werden hitobito/hitobito#1435
* [ ] Da es potenziell zehntausende Empfänger gibt, soll der Job nur 1 Empfänger als "bearbeitet" markieren und dann das Mail an diesen Empfänger verschicken. Ein nächster Job arbeitet dann das nächste Mail ab etc. hitobito/hitobito#1435

**Comment by olibrian** [comment]
Lösung vor dem Go-Live:
* Mailversand wird deaktiviert #132 
* Rechnungen können entweder direkt via Abo generiert und verschickt werden oder anschliessend im Rechnungsmodul

**Comment by chrusu** [comment]
@olibrian Was passiert mit den Haushalten bei der Option auf Email-Versand?

**Comment by carlobeltrame** [comment]
Vorschlag: Beim E-Mail-Versand werden Haushalte ignoriert, also an jede Person ein einzelnes Mail versendet. Haushalte haben ja keine gemeinsame Mailadresse.

**Comment by ThomasEllenberger** [comment]
Dieses Anliegen ist bei der Mitte aktuell kein Thema mehr.
Da auch die verlinkten Issues bereits als nicht geplant geschlossen wurden, schliess ich auch dieses.
