### ISSUE TITLE
Datenmigration

### ISSUE THREAD

**Issue by olibrian** [hitobito/hitobito_die_mitte#14]
Ziel: Übernahme der bestehenden CSV Daten aus aktuellem System. Dabei soll die Produktionsumgebung sukzessive mit Produktiv Daten gefüllt werden. Folgendes Vorgehen ist angedacht

- [x] Setup sodass CVS wiederholt und auf einfache Weise eingespielt werden kann
- [x] Grobsichtung der CSV Daten, Identifizikation der relevanten Datein für Gruppen / Personen / Rollen #4 
- [x] Import der Gruppen inklusive Mapping auf Struktur so wie sie in hitobito definiert wurde, siehe #48  
- [x] Import der Mitgliedschaften, sodass entsprechende Rollen für Personen erstellt werden können #52
- [x] Vorgehen für Strukturkonflikt Quelle(Ordner, Merkmal), Ziel (GroupType, RoleType) #67
- [x] Import der Personen bezogenen Stammdaten, siehe #49
- [x] Import der Merkmale, sodass weitere Rollen für Personen erstellt werden können #66
- [x] Import der Kampagnen / Rechnungen #68 
- [x] Import der SpendenHistorie  #69 
- [x] Sekretäre gemäss Liste von Stefan hinzufügen
- [x] Weiter Merkmale gemäss CSV Mappen
- [x] Gesamten Baum importieren
- [x] Inaktive Merkmale #72
- [x] Diskussion / Bereinigungen der Strukturanpassungen von #48 
- [x] Symp nach kant Statut löschen #77 
- [x] Personen fälschlicherweise als Firma erkannt #73
- [x] Nur Personen mit gleichem Nachnamen als Familie abbilden #79
- [x] Korregierte Group Mappings #78
- [x] Doubletten automatisch bereinigen #75
- [x] Weiter Anpassung an Gruppen Struktur #80
- [x] Empfänger als Abo #76 
- [x] Merkmale die nicht auf den Gruppentyp passen #74
- [x] Weiter Anpassung an den Rollen #89 
- [x] Personen mit Merkmal Juristen werden in einer Arbeitsgruppe "Juristen" als Mitglieder importiert
- [x] Personen mit Merkmal Empfänger sollen nicht in der fallback Arbeitsgruppe landen, sondern Gruppe soll bestehenden bleiben Personen werden dort als Mitglieder geführt.  
- [x] Am Enden sollen keine Merkmal Rollen mehr vorkommen
- [x] Gruppe Gewählte in der Region und der Vereinigung gibt es nicht, in Arbeitsgruppe umwandeln
- [x] Korrespondenzsprache überprüfen / richtig setzen
- [x] Rollen in der README aktualisieren
- [x] Sekretäre CSV Liste importieren
- [x] Attribut Korrespondenzsprache übernehmen
- [x] Attribut Titel übernehmen, haben wir hier Daten vom OM?
- [x] Rollen CSV Liste importieren
- [x] Root user seeden
- [x]  Anrede statisch auf Titel Nachname setzen
- [x] Inaktive Rollen: Teilweise übernommen (siehe Mail von Stefan, 15.03.21)
- [x] Familienlogik OM vs. Hitobito: Teilweise übernommen (siehe Mail von Stefan, 15.03.21) (-> Mitgliedschaft für andere Haushaltsmitglieder duplizieren?)
- [x] Neue Seed Daten einlesen

Weiters Vorgehen
- [x] Korrigieren der falschen Seed daten
- [x]  PW reset Link verschicken am geseedete Rollen 
- [x] Kanton Luzern gibt es die Arbeitsgruppe «Vereinigungen/Kommission» dort drin sind Movimento, CDK und LWK.  (siehe Mail von Stefan, 15.03.21) -> unklar -> ist bei Stefan, er schaut mit dem Kanton Luzern und kommt bei Bedarf wieder auf uns zu.
