### ISSUE TITLE
MESSAGE: Rückmeldung Anpassungen Brief

### ISSUE THREAD

**Issue by olibrian** [hitobito/hitobito_die_mitte#190]
0. Abstand zwischen Betreff und Datum, Ort. Gerne derselbe Abstand, der zwischen Betreff und Anrede ist.
1. Die Absenderzeile sollte so lang sein, wie möglich also max. so lang wie ein Fenster in einem Couvert. Ein Fenster ist 100 mm lang. je 5 mm sollte der Abstand auf beiden Seiten sein, also maximale Länge 90mm, ist dies bereits so?
2. Zudem kann das Post CH AG noch etwas runter und etwas mehr nach rechts.
3. Die Fusszeile muss zudem genug breit sein, dass eine IBAN Nummer drin Platz findet. Wir haben Schriftgrösse 8 für Fusszeilen, grösser muss dass bei euch also auch nicht sein, dann kann dies noch etwas zusammenrücken.

# ToDos

- siehe (core) app/domain/export/pdsf/messages/letter/header.rb
	- [x] Abstand Betreff und Datum/Ort anpassen
	- [x] Absenderzeile ggf. anpassen
	- [x] Shipping-Info anders positionieren (passt das mit den Specs von der Post?)
- siehe (wagon) app/domain/die_mitte/export/pdf/messages/letter/footer.rb
	- [x] mit IBAN testen
	- [x] Schriftgrösse reduzieren

Für grössere Umbauten bitte Rücksprache und ggf. neues Ticket.
