### ISSUE TITLE
INVOICE: Anreden

### ISSUE THREAD

**Issue by mlue00** [hitobito/hitobito_die_mitte#198]
Als Person, welche häufig Briefe und Rechnungen verschickt wünsche ich mir eine angepasste Auswahl der möglichen Anreden, um den Adressat:innen besser gerecht zu werden.

Neu sollen folgende Anreden verfügbar sein:

1) Hallo {Vorname} → bereits vorhanden
2) Liebe*r {Vorname} → bereits vorhanden
3) Sehr geehrte*r Frau*Herr {Name} → Neu
4) Sehr geehrte*r Frau*Herr {Titel} {Name} → bereits vorhanden

Übersetzungen sind wie folgt:
Erste Form ist weiblich, zweite männliche

Französisch
1) Bonjour {Vorname}
2) Chère*Cher {Vorname}
3) Chère Madame,*Cher Monsieur,
4) Madame,*Monsieur,

Italienisch
1) Ciao {Vorname}
2) Cara*Caro {Vorname}
3) Stimata Signora {Name}*Stimato Signor {Name}
4) Gentile Signora {Name}*Egregio Signor {Name} 

# Tech-Spec

- Die bereits existierenden Anreden können entsprechend angepasst, ergänzt oder beibehalten werden.
- Umsetzung im Mitte Wagon

# ToDo

- [x] Neue Variante in https://github.com/hitobito/hitobito_die_mitte/blob/master/config/locales/models.die_mitte.de.yml#L488 eintragen
- [x] Alle Varianten in derselben Datei gemäss Ticket anpassen
- [x] Änderungen analog für französisch und italienisch umsetzen (achtung: gleiche Keys verwenden wie in deutsch)
- [x] Mit angemessener Rolle "durchklicken"
- [x] CHANGELOG-Eintrag unter "unreleased" unten hinzufügen
- [ ] Feedback der Mitte anfragen und entsprechend ergänzen & anpassen
