### ISSUE TITLE
EXPORT: Nur ausgewählte Rollen exportieren

### ISSUE THREAD

**Issue by mlue00** [hitobito/hitobito_die_mitte#202]
Timebox: 4h

In den Exports wird in der Spalte "Rolle" sämtliche Rollen einer Person angezeigt. Wenn eine Person sehr viele Rollen hat, ist dies nicht sehr übersichtlich. 
Neu sollen in einer neuen Spalte nur jene Rollen auf der Liste erwähnt, die für das Erstellen der Liste angewählt wurden. Im Abo sind dies die ausgewählten Rollen, bei einem Export aus einer Gruppe sind es nur die Rollen der Gruppe, etc.

# Tech-Spec

- Umsetzung im Mitte Wagon, da Information in den Exports verloren geht die für andere Organisationen nützlich sein könnte
- Die Rollen werden in der Personenliste und bei Abos unterschiedlich preloaded:
  - Bei Personenlisten machts `preload_groups` hier: https://github.com/hitobito/hitobito/blob/master/app/domain/person/filter/list.rb#L22. Dieses könnte man im Mitte Wagon einfach zu entfernen versuchen (Achtung, gut nach Seiteneffekten testen)
  - Bei Abos ists etwas komplizierter. Die Rollen werden in https://github.com/hitobito/hitobito/blob/master/app/domain/mailing_lists/subscribers.rb#L27..L45 gejoint mit LEFT JOINs. Möglicherweise könnte man einzelne dieser LEFT JOINs auf INNER JOINs ändern und dann wäre die Anforderung erfüllt. Möglicherweise reicht das aber auch noch nicht. Ausserdem gut nach Seiteneffekten testen.

# ToDo

- [x] Konkretes Umsetzungs-Ticket konzipieren
- [ ] Specs schreiben
- [ ] Mit angemessener Rolle "durchklicken"
- [ ] CHANGELOG-Eintrag unter "unreleased" unten hinzufügen

**Comment by carlobeltrame** [comment]
Das kann hitobito doch schon dachte ich..? Wenn man einen Rollenfilter aktiv hat und dann exportiert müssten nur die gefilterten Leute exportiert werden.

**Comment by olibrian** [comment]
> Das kann hitobito doch schon dachte ich..? Wenn man einen Rollenfilter aktiv hat und dann exportiert müssten nur die gefilterten Leute exportiert werden.

Jein. Jedoch wird von jeder Person immer alle Rollen exportiert. Ziel dieses Issues ist es den  Rollenfilter zu exportieren. Beispiel: Ich mache einen Export von allen Präsident und Kassier. Dabei erhalten ich aktuell in der Spalte "Rolle" jeweils alle Rollen pro Person. Neu soll in einer neuen Spalte die Rolle Präsident oder Kassier exportiert werden. Andere Rollen welche die Person hat sollen in dieser Spalte nicht aufgeführt sein.

**Comment by TheWalkingLeek** [comment]
Issue generiert: https://github.com/hitobito/hitobito_die_mitte/issues/213

**Comment by mtnstar** [comment]
@TheWalkingLeek habe das Issue #213 mal noch etwas angepasst.
wollen wir das noch gemeinsam besprechen bevor wir hier dieses Issue dann schliessen?
