### ISSUE TITLE
INVOICES: Sortierung Rechnungsbriefe

### ISSUE THREAD

**Issue by mlue00** [hitobito/hitobito_die_mitte#203]
Als rechnugsstellende Person bei der Mitte möchte ich, dass die Rechnungsbriebe beim PDF-Download automatisch, alphabetisch nach Nachnamen sotiert werden, um die Übersichtlichkeit zu gewährleisten.

Neu soll der PDF-Download der Rechnungsbriefe alphabetisch nach Nachnamen sotiert werden. 

# Tech-Spec

- Umsetzung im Core
- Rechnungsbriefe im PDF-Download automatisch sortiert
- Sortierung nach Nachnamen
- Haushalte gibt es im Rechnungsbrief nicht als PDF (spielt daher keine Rolle)

# ToDo

- [ ] In https://github.com/hitobito/hitobito/blob/master/app/domain/export/pdf/messages/letter.rb#L123 eine Sortierung nach `person.last_name` einbauen
- [ ] Specs schreiben
- [ ] Mit angemessener Rolle "durchklicken"
- [ ] CHANGELOG-Eintrag unter "unreleased" unten hinzufügen
