### ISSUE TITLE
INVOICES: Anpassung Formel Bisherspenden

### ISSUE THREAD

**Issue by mlue00** [hitobito/hitobito_die_mitte#204]
Als Person mit Finanzberechtigungen bei der Mitte
möchte ich, dass für die Berechnung der Bisherspendenden (aka Variabler Spendenaufruf) der Median der Zahlungen verwendet wird um eine bessere Schätzung der Spenden zu erhalten.

Neu soll der Median der Zahlungen für die Berechnung der Bisherspendenden angenommen werden.
Bisher wurde hierfür die Summe verwendet.

Grundlage für die Berechnung ist die Einstellung in der `invoice_config`

![image](https://user-images.githubusercontent.com/9592347/184307950-226814c8-61dd-4049-9284-22b3a9fed831.png)

Der Bisherspenden wird via Abo und Rechnungsbrief ausgelöst.

Konkretisierung: Aktuell wird pro Jahr jeweils die Summe der Zahlungen genommen. Falls mehrere Jahre berücksichtigt werden, wird der Durchschnitt über die Jahre gerechnet. Neu soll über sämtliche Zahlungen der Periode der Median genommen werden.

# Tech-Spec

- Median der Zahlungen für die Berechnung der Bisherspendenden
- Summe nicht mehr relevant

# Fragen

- [x] Wo ist diese Zahl sichtbar? -> Ticket oben aktualisiert
- [x] Ist das eine Anpassung für den Core oder nur für die Mitte? -> ist im core

# ToDo

- [x] Domainklasse `Payments::Collection` anpassen
  - [x] neue Methode `median_payment` mit "increased_by"-option
  - [x] [Median](https://de.wikipedia.org/wiki/Median) der Zahlungen wird für die Berechnung verwendet
  - [x] `previous_payments` entfernen, wenn von keinem Wagon ausser "Die Mitte" verwendet
- [x] Specs anpassen und ggf. neue schreiben
- [x] Mit angemessener Rolle "durchklicken"
- [x] CHANGELOG-Eintrag unter "unreleased" unten hinzufügen

**Comment by kronn** [comment]
https://stackoverflow.com/a/14859546/674840
