### ISSUE TITLE
INVOICES: 360° Sicht

### ISSUE THREAD

**Issue by mlue00** [hitobito/hitobito_die_mitte#205]
Sichtbarkeit von Tab Rechnungen. 

Personen mit `:finance`-Ability sehen das Tab bei Personen im ganzen Layer (ohne Layer unterhalb)
Auf der eigenen Person soll dieses Tab immer sichtbar sein.

https://help.puzzle.ch/#ticket/zoom/4338 beschreibt das Problem noch mit konkreten Personennamen.

Der Fehler scheint im Zusammenhang mit https://github.com/hitobito/hitobito/issues/474 entstanden zu sein. Hier scheint die Ursache zu sein:

https://github.com/hitobito/hitobito/blob/da6bb02636fc203628b320c221549dcf50e75302/app/helpers/sheet/person.rb#L26

Es könnte sein, dass hier statt `person.finance_groups.present?` eher `current_user.finance_groups.present?` gemeint ist. Dieser check sollte aber ohnehin in die `InvoiceAbility`.

# Tech-Spec

- Verschickte Rechnungen können auf einer Person angezeigt werden.
- Es werden Rechnungen der entsprechenden Ebene angezeigt.
- Personen mit Finanzberechtigungen sehen die Rechnungen. 
- Man sieht seine eigenen Rechnungen

# Fehlerbeschreibung

![](https://user-images.githubusercontent.com/9592347/177573546-98f1c169-7143-40e5-bce1-836fd6e274c5.gif)

# Referenzen

- hitobito/hitobito#1776
- hitobito/hitobito#1803

# ToDo

- [x] `InvoiceAbility` anpassen, um die Berechtigung nur dort zu kapseln
- [x] Sichtbarkeit vom Tab "invoices" anpassen
- [x] Specs schreiben
- [x] Mit angemessener Rolle "durchklicken"
- [x] Mit Root-User durchklicken, um erneuten Bug auszuschliessen
- [x] CHANGELOG-Eintrag unter "unreleased" unten hinzufügen

**Comment by carlobeltrame** [comment]
Auf jeder Person? Ist das nicht dasselbe wie #1803?

**Comment by olibrian** [comment]
Wurde bereits im https://github.com/hitobito/hitobito/issues/1803 und https://github.com/hitobito/hitobito/issues/1776 ausführlich beschrieben. Mit dem Abschluss von diesem Ticket sollten die beiden anderen obsolet werden.

**Comment by richardjubla** [comment]
Hinweis zum jubla-Wagon oder Instanzen welche das Rechnungs-Modul nicht verwenden. Der Tab Rechnungen auf der Person kann schon immer sichtbar sein, WENN das Rechnungs-Modul verwendet wird. 
Bei uns ist der Tab Rechnungen aktiv, obwohl wir das Rechnungs-Modul nicht verwenden.
