### ISSUE TITLE
EBICS: Umgang mit nicht zuweisbaren Zahlungen

### ISSUE THREAD

**Issue by mlue00** [hitobito/hitobito_die_mitte#206]
Als Person mit Finanzverantwortung bei der Mitte
möchte ich monatlich eine Liste der nicht zugewiesenen Zahlungen erhalten um diese kontrollieren und allenfalls unnötige Mahnungen vermeiden zu können. 

Neu soll monatlich mittels Scribt eine Liste der nicht zugewiesenen Zahlungen exportiert und an die Mitte verschickt werden. 

# Tech-Spec

- Nicht zugewiesene Zahlungen sollen als Liste exportiert werden können. 
- Liste soll monatlich an die Mitte verschickt werden.

# ToDo

- [ ] Nicht zugewiesene Zahlungen können als Liste exportiert werden.
- [ ] Liste wird monatlich an die Mitte verschickt.
- [ ] Specs schreiben
- [ ] Mit angemessener Rolle "durchklicken"
- [ ] CHANGELOG-Eintrag unter "unreleased" unten hinzufügen

**Comment by olibrian** [comment]
Wird durch https://github.com/hitobito/hitobito_die_mitte/issues/206 geschlossen

**Comment by carlobeltrame** [comment]
> Wird durch https://github.com/hitobito/hitobito_die_mitte/issues/206 geschlossen

Das hier _ist_ #206..?

**Comment by olibrian** [comment]
Natürlich das hier: https://github.com/hitobito/hitobito/issues/1789
