### ISSUE TITLE
INVOICES: Analyse Differenz zwischen allen per EBICS empfangen Zahlungen und der DB

### ISSUE THREAD

**Issue by olibrian** [hitobito/hitobito_die_mitte#210]
## Aktuelles Verhalten

Analyse via EBICS Empfangenden Zahlungen und der in der DB gespeicherten Zahlungen. Zeitraum ist  der Juli 2022.

Ziel: Mögliche Pattern erkennen, um die Differenz zu erklären. 

## Tech-Spec

- Erster Approach: DB Dump ziehen, Alle Zahlungen löschen, Zahlungen vom Juli per EBICS reempfangen und importieren. Anschliessend mit Prod DB vergleichen
- Mögliche Faktoren:
  - Rechnungen auf falscher Ebene
  - Referenznummer beim Einzahlen falsch abgetippt
  - Validierung `reference: unique` auf Payment..

## ToDo
- [ ] Erster Approach durchführen
- [ ] Mögliche Faktoren überprüfen
- [ ] Versuchen eine Aussage zu machen
