### ISSUE TITLE
INVOICE: Rechnungsadresse links/rechts ausrichten

### ISSUE THREAD

**Issue by olibrian** [hitobito/hitobito_die_mitte#211]
## Aktuelles Verhalten

Die Einstellungen für die Briefe `https://die-mitte.puzzle.ch/de/groups/1/settings` ist beim Wagon der Mitte kein Dropdown sondern ein Freitext. Beim rendern der Rechnung wird gewisser Text überschrieben:
Beispiel: https://die-mitte.puzzle.ch/de/groups/1/invoices/27160.pdf?ids=27160&singular=true

![image](https://user-images.githubusercontent.com/9592347/189070323-d4764aeb-638c-48c1-8e2b-32f93ff3d984.png)

Das gleiche tritt bei der MT Instanzen auf.

## Gewünschtes Verhalten

Die Einstellung soll ein Dropdown wie im Core sein. Bei den Rechnungen darf sich der Text nicht überlagern.

## Schritte zum reproduzieren

1. Login auf der Integration der Mitte (die-mitte.puzzle.ch)
2. Unter Einstellungen auf einem Layer die Briefe-Einstellungen anschauen
3. Rechnung generieren

# Tech-Spec

Addressposition wird seit neuerem (https://github.com/hitobito/hitobito_sww/issues/59) durch Gruppeneinstellungen gesteuert

# ToDo

Wahrscheinlich durch https://github.com/hitobito/hitobito/pull/1814/files reingekommen

- [x] PR anschauen
- [x] Überprüfen ob das GroupSetting `nil` beim PDF rendern richtig handled
- [x] Überprüfen ob überall das `Export::Pdf::AddressRenderers` Module beim Addresse rendern verwendet wird
- [ ] Roni vom ECB informieren
