### ISSUE TITLE
PEOPLE: Nur relevante Rollen exportieren

### ISSUE THREAD

**Issue by TheWalkingLeek** [hitobito/hitobito_die_mitte#213]
Dieses Umsetzungs-Issue basiert auf der Diskussion in #202 

# Ausgangslage

Beim Export von Personen werden aktuell in der Spalte "Rollen" sämtliche Rollen einer Person aufgelistet. Einige Personen haben viele Rollen was den Export dann sehr unübersichtlich macht.

# Soll

Es werden nur die Rollen aus dem aktuellen Filter/Gruppe in der Spalte Rollen aufgelistet.

![image](https://user-images.githubusercontent.com/655627/194091206-8ea8f985-0bdb-462c-ac98-b76b9706f904.png)

Dieses Verhalten kann via einer Checkbox vom Benutzer gesteuert werden. Beim Wagon Der-Mitte ist diese Option standardmässig ausgewählt, sonst nicht. 

Nur Excel, CSV Exporte von Personen in:

1. Personenlisten
2. Abos
3. ~~Event-Teilnehmern~~ Nach Absprache mit tellenberger lassen wir das für dieses Ticket erstmal bleiben, da bei dem Export sowieso eine Inkonsistenz zwischen dem Export von `Group::Role` und `Event::Role` besteht
 
nur noch die jeweils relevanten Rollen angezeigt werden. Heisst:
1. Nur noch die Rollen der entsprechenden Gruppe oder des entsprechenden Filter auf der Personenliste
2. Die Rollen welche zur Abo Zugehörigkeit führen

# Tech-Spec

- Umsetzung im Core, Standardmässig ist die Option abgewählt
- Ermöglichen das in einem Wagon die Option standardmässig ausgewählt ist
- ~~Preloading der Rollen verhindern~~ Leider schlecht möglich da die Rollen sowieso spätestens bei der Ability alle geladen werden
- Als neuer Parameter der relevanten Tabular Exporte und deren Row Klassen das Argument `options = {}` einführen
- Beim Initialisieren des Exporters (& ExporterJobs) `relevant_group_ids` & `relevant_role_types` als Optionen mitgeben

# ToDo

## Allgemein

- [x] `Export::Tabular::Base#initialize`, `Export::Tabular::Row#initialize` anpassen damit eine Liste von Rollen die angezeigt werden sollen mitgegeben werden kann
- [x] `Export::Tabular::People::PersonRow#roles` anpassen und Rollen entsprechend `relevant_role_types` herausfiltern. Die Argumente dürfen aber weiterhin optional bleiben
- [x] Im SubscriptiosController die neue Option berücksichtigen und Liste der Rollen an den Export liefern falls ausgewählt
- [x] Im PeopleController die neue Option berücksichtigen und Liste der Rollen an den Export liefern falls ausgewählt
- [x] CHANGELOG-Eintrag unter "unreleased" unten hinzufügen
- [x] Mit angemessener Rolle "durchklicken"
- [x] Prüfen ob für alle Cases Specs vorhanden sind
