### ISSUE TITLE
Datenerfassung

### ISSUE THREAD

**Issue by olibrian** [hitobito/hitobito_die_mitte#6]
- [x] Attribute auf der Person definieren #43
- [x] Attribute auf der Organisation definieren #44
- [x]  Post Verzeichnis importieren #17
- [x] F02-15 Beim erfassen Adressenvervollständigung vornehmen (Ajax) #18
- [x] F02-16 Nächtliche Address Prüfung via Job #19
- [x] F02-29 Globales Tag (Stichwort) Management #21
- [x] Familienadressen #53
