### ISSUE TITLE
Korrespondenz Briefmodul

### ISSUE THREAD

**Issue by olibrian** [hitobito/hitobito_die_mitte#8]
Ziel: Brief an gewisse definierte Personen schicken. Auswahl von Empfänger durch ein Abo. Beim Erstellen eines Briefs kann der Inhalt in einem WYSIWYG Editor (bold, Absatz, mit Logo) definiert werden. Der Absender ist auf dem Layer entsprechend definiert. Für die Erstellung können Platzhalter (Anrede, Name, Vorname) verwendet werden. Optional kann eine Rechnung angehängt werden. Der Brief kann als PDF generiert oder an die Druckerei übermittelt werden.

**Voraussetzung:**

- [x] Messages Model #84
- [x] ActionText

**Brief**

- [x] Briefe erstellen und Anzeigen #85
- [x] Platzhalter im Brief #85 
- [x] Vorschau auf Brief #85
- [x] Brief Versand Vorbereiten #86
- [x] Brief als PDF generieren #88
- [x] F04-01 Vorlagen mit entsprechenden Gestaltungsmöglichkeiten #24 
- [x] Bild im Editor #92
- [x] Platzhalter per Click einfügen #93 (Nice to have)

**Integration Rechnung**

- [x] Briefe mit Rechnungen #83 / #87 
- [x] Erstellen der Sammelrechnung und Einzelrechnungen  #90
- [ ] Berechnung der Artikel Summe  beim Formular ergänzen
- [ ] Ev.  Artikel in der PDF Rechnung anzeigen
- [ ] Ev.  Darstellung der Nachricht (show seite) anpassen

**Integration CVP**
- [x] Salutation Platzhalter hinzufügen #91 

**Versand**

- [x] F04-05 Korrespondenz auf Personen und Firmen sichtbar, Kommunikationshistorie #28
- [x] F04-03 Anbindung an Druckerei (Suter & Gerteis AG) #26 
- [x] F04-02 Serienbriefe erstellen und an lokalen Drucker übergeben #25 
- [x] Optional: Briefe per EMail versenden #86
- [x] F04-04 Erzeugtes Schriftgut im System speichern #27

**User Acceptance Test**

- [x] Brief in Abo erstellen
- [x] Brief als PDF generieren
- [x] Brief an 20 Empfänger erstellen
- [x] Brief an 1'000 Empfänger erstellen
- [ ] Brief an 100'00 Empfänger erstellen
- [x] Brief mit Rechnung generieren
- [x] Rechnung per Mail verschicken
- [ ] Testbrief an Druckerei

**Comment by ninfaj** [comment]
Hier eine erste Skizze wie das Briefmodul aussehen könnte:
![image](https://user-images.githubusercontent.com/157533/95314448-98b1c780-0891-11eb-9b5e-e02671e5ded6.png)

> - Der Verlauf ist jeweils pro Brief gedacht, damit der Benutzer weiss, ob / wann / wie er ihn verschickt hat
> - Einsetzen von Platzhaltern wird vermutlich direkt über den Editor gemacht?

**Hier noch zwei kleine Fragen:**
- Wie sind die Berechtigungen der gespeicherten Briefen? Kann jeder auf alle Briefe zugreiffen, oder ist das innerhalb der Gruppe?
- Können Briefvorlagen auch eigenhändig angepasst / verwaltet werden, oder sind die fix vom System vorgegeben?

**Comment by carlobeltrame** [comment]
Technische Notizen:
* Das PDF wird nicht als Datei gespeichert, sondern immer on the fly generiert
* Der "Vorschau"-Link sendet einen remote POST Request ans Backend, welches den noch nicht gespeicherten Briefinhalt in ein PDF verpackt und als Response zurückliefert. Das PDF wird inline dargestellt, sodass der User nicht ermutigt wird, direkt dieses PDF auszudrucken.
* Die Buttons zum Auftrag erteilen und PDF herunterladen sind deaktiviert, sobald etwas am Briefinhalt geändert wird; nur nachdem der Brief gespeichert ist können diese benutzt werden.
* Sobald entweder das PDF heruntergeladen wird oder ein Druckauftrag erteilt wird, werden die aktuellen Abonnenten der MailingList in die `message_recipients` des Briefs übertragen, und der Briefinhalt kann von da an nicht mehr bearbeitet werden.
* Will der User nachträglich trotzdem noch etwas am Inhalt ändern, muss er den Status zurücksetzen bzw. manuell bestätigen, dass das PDF nicht ausgedruckt und versendet wurde oder der Druckauftrag abgesagt wurde (User Interface dafür muss noch definiert werden)
* Will der User einen ähnlichen Brief aufsetzen und erneut versenden, so muss er den Brief duplizieren.
