### ISSUE TITLE
Korrespondenz Rechnungen

### ISSUE THREAD

**Issue by olibrian** [hitobito/hitobito_die_mitte#9]
Ziel: Ergänzen von Rechnungsmodul für die Anforderungen der CVP. Es werden nur QR Rechnungen benötigt.
- [x] F04-08 Vorlagen für Mahnungen #29 
- [x] Gruppieren von Rechnungen (aus Modul Kampagnen) #54 
- [x] F02-21 Mahnstop auf Rechnung #20

**Comment by olibrian** [comment]
Ursprüngliche Anforderung aus dem RFI:

* Das System erlaubt das Erstellen von Schriftgutvorlagen inklusive auf den Strukturbaum bezogenen ESR-Teil mit entsprechenden Gestaltungsmöglichkeiten.
* Der Umbau auf QR-Rechnungsdokumente ist im Angebotspreis enthalten, sobald deren Layout final bekannt ist.
* Das System nutzt eine entsprechende Vorlage für Rechnungen/Mahnungen automatisch. -> Antwort Puzzle: Wir verwenden zur Zeit eine generische Vorlage, welche auf die Anforderungen angepasst werden kann. Natürlich sind Absender, Texte, etc pro Gruppe konfigurierbar.

* Erzeugte Rechnungen/Mahnungen werden in einer geeigneten Form im System gespeichert.
